### ISSUE TITLE
Add setting for changing ollama address.

### ISSUE THREAD

**Issue by hgaiser** [elevenhsoft/cosmic-applet-ollama#2]
My ollama is running on a different device, which I would like to access remotely. However the ollama address is currently [hardcoded](https://github.com/elevenhsoft/cosmic-applet-ollama/blob/37a7ff5dd7bd882e1a0f7765fb6c1d70fa002250/src/api.rs#L52).

Adding a setting for changing this address would allow to run ollama on a different system.

**Comment by elevenhsoft** [comment]
Hello,

Yes. That's good idea and basically should be done on the beginning ^^ I will add an input to settings to change this.

**Comment by hgaiser** [comment]
Thanks! And thanks for this applet. Been having a lot of fun with it :).

**Comment by elevenhsoft** [comment]
Just added this input, we can close i guess :) https://github.com/elevenhsoft/cosmic-applet-ollama/commit/c635a0534294bec419a1390eac99b08a867bd012
